project_id = "gvftdfriujrkpptdueyb"
[functions.trigger-make-run]
enabled = true
verify_jwt = true
import_map = "./functions/trigger-make-run/deno.json"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/trigger-make-run/*.html" ]
