// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Use stable Supabase URLs to prevent DNS resolution issues
const SUPABASE_URL = "https://gvftdfriujrkpptdueyb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2ZnRkZnJpdWpya3BwdGR1ZXliIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0NDkzOTIsImV4cCI6MjA3MzAyNTM5Mn0.NrjUlE8YB-M7pspX0We2kikfYDTvngqezR6hPhFna0k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});